const dare = [
`ngobrol dengan salah satu temenmu selama 10 menit`, 
`tantang salah satu temanmu baca Al ikhlas bagi yang islam`,
`suruh ganti foto temanmu di grup dengan foto ini https://pbs.twimg.com/media/ExubEtpVcAcYHZ8.jpg selama 1 hari`,
`Kirim pesan ke mantan kamu dan bilang "aku masih suka sama kamu`,
`telfon crush/pacar sekarang dan ss ke pemain`,
`baca surat Al-kautsar dan kirim berupa vn (Bagi yang islam)`,
`Bilang "KAMU CANTIK BANGET NGGAK BOHONG" ke cowo`,
`ss recent call whatsapp kamu`,
`drop emot "🦄💨" setiap ngetik di gc/pc selama 1 hari`,
`Sumbangkan uang sisa jajan ke orang tidak mampu`,`drop kutipan lagu/quote, terus tag member yang cocok buat kutipan itu`,
`pake foto sule sampe 3 hari`,
`ketik pake bahasa daerah 24 jam`,
`ganti nama menjadi "gue anak lucinta luna" selama 5 jam`,
`chat ke kontak wa urutan sesuai %batre kamu, terus bilang ke dia "i lucky to hv you`,
`prank chat mantan dan bilang " i love u, pgn balikan`,
`record voice baca surah al-kautsar`,
`bilang "i hv crush on you, mau jadi pacarku gak?" ke lawan jenis yang terakhir bgt kamu chat (serah di wa/tele), tunggu dia bales, kalo udah ss drop ke sini`,
`sebutkan tipe pacar mu!`,
`snap/post foto pacar/crush`,
`teriak gajelas lalu kirim pake vn kesini`,
`pap mukamu lalu kirim ke salah satu temanmu`,
`kirim fotomu dengan caption, aku anak pungut`,`teriak pake kata kasar sambil vn trus kirim kesini`,
`teriak " anjimm gabutt anjimmm " di depan rumah mu`,
`ganti nama jadi " BOWO " selama 24 jam`,
`Pura pura kerasukan, contoh : kerasukan maung, kerasukan belalang, kerasukan kulkas, dll`,
`Cium salah satu kaus kaki di antara kita.`,
`Makan satu gigitan kulit pisang. terus kamu videoin disini`,
`Peragakan salah satu orang di antara kita sampai ada yang bisa menebak siapa orang yang diperagakan.`,
`Katakan ‘meong’ di setiap akhir kalimat sampai giliranmu yang selanjutnya`,
`Tirukan seorang selebriti sampai ada yang bisa menebak.`,
`Bertingkahlah seperti ayam sampai giliranmu yang selanjutnya.`,
`Biarkan satu orang menggambar tato di wajahmu.`,
`Lakukan rap gaya bebas selama 3 menit.`,
`Biarkan orang lain membuat status menggunakan akun sosial mediamu.`,
`Berikan ponselmu kepada salah satu di antara kita dan biarkan orang tersebut mengirim satu pesan kepada siapapun yang dia mau.`,
`Tutup mata, lalu raba muka salah satu di antara kita, sampai kamu bisa menebak siapa orang itu!`,
`Ungkapkan perasaan kamu buat gebetanmu! pake vn di grup`,
`Push up 20 kali. lalu video kirim ke grup`,
`Telepon seorang teman, dan katakan selamat ulang tahun sambil menyanyikan lagu.`
]
module.exports = dare;