const truth = [
`Menurutmu temanmu sendiri kamu anggap sebagai keluarga nga?`,
`Pernah suka sama siapa aja? berapa lama?`,
`Kalau boleh atau kalau mau, di gc/luar gc siapa yang akan kamu jadikan sahabat?(boleh beda/sma jenis)`,
`apa ketakutan terbesar kamu?`,
`pernah suka sama orang dan merasa orang itu suka sama kamu juga?`,
`Siapa nama mantan pacar teman mu yang pernah kamu sukai diam diam?`,
`pernah gak nyuri uang nyokap atau bokap? Alesanya?`,
`hal yang bikin seneng pas lu lagi sedih apa`,
`pernah cinta bertepuk sebelah tangan? kalo pernah sama siapa? rasanya gimana brou?`,
`pernah jadi selingkuhan orang?`,`hal yang paling ditakutin`,
`siapa orang yang paling berpengaruh kepada kehidupanmu`,
`hal membanggakan apa yang kamu dapatkan di tahun ini`,
`siapa orang yang bisa membuatmu berfikir negatif`,
`siapa orang yang pernah buatmu sange`,
`(bgi yg muslim) pernah ga solat seharian?`,
`Siapa yang paling mendekati tipe pasangan idealmu di sini`,
`suka mabar(main bareng)sama siapa?`,`pernah nolak orang? alasannya kenapa?`,
`Sebutkan kejadian yang bikin kamu sakit hati yang masih di inget`,
`pencapaian yang udah didapet apa aja ditahun ini?`,
`kebiasaan terburuk lo pas di sekolah apa?`,
`Acara TV apa yang paling kamu benci? Beri tahu alasannya!`,
`Kapan terakhir kali kamu berbohong?`,
`Kapan terakhir kali kamu menangis?`,
`Kapan terakhir kali kamu kentut?`,
`Apa ketakutan terbesarmu?`,
`Apa fantasi terbesar atau terhanehmu?`,
`Apa hal yang membuatmu senang orangtuamu tidak mengetahuinya?`,
`Pernahkah kamu selingkuhin pacarmu?`,
`Apa hal paling lebih terburuk yang pernah kamu lakukan?`,
`Apa rahasia yang tidak pernah kamu ceritakan kepada siapapun?`,
`Apakah kamu punya bakat terpendam?`,
`Apa pendapatmu tentang perselingkuhan? jawab dengan jujur`,
`Apa pengalaman intim terburuk yang pernah kamu alami?`,
`Apa hal yang paling membuatmu merasa insecure?`,
`Pengen jadi anime apa? kalo dah gede?`,
`Kenapa kamu putus dengan mantan yang sebelumnya? berikan alasannya`,
`Hal terburuk apa yang pernah dilakukan orang terhadapmu?`,
`Apakah kamu pernah melanggar hukum alam?`,
`Apa hal paling memalukan yang pernah kamu lakukan? Kapan?`,
`rahasia yang tidak pernah kamu ceritakan kepada siapapun tentang percintaan?`,
`Siapa orang yang paling ingin kamu cium di antara kita?`,
`Apakah orang tuamu perokok berat?`,
`Anime apa yang ingin anda idamkan bagimu?`,
`Apakah didaerahmu ada anggota PKI, kalo tidak ada skip`,
`apakah pernah kamu hamil dimasa dini? khusus perempuan`,
`Bagaimana rasanya anda jadi beban keluarga?`,
`Kalau kamu bisa jadi tidak terlihat, apa hal pertama yang akan kamu lakukan?`,
`Menurutmu, hewan apa yang terlihat paling mirip denganmu?`,
`Siapa orang yang ingin kamu jadikan istri/suami?`,
`Menurutmu bagas kamu angap teman atau keluarga?`,
`Apa nama ku di kontak HP mu?`,
`Siapa first date atau pacar pertamamu?`,
`Film/serial/drama/anime paling memalukan yang pernah kamu tonton?`,
`Apa hal pertama yang kamu lihat saat kamu melihat orang lain (lawan jenis)?`,
`Apakah kamu pernah diam-diam suka dengan salah satu anak tongkrongan yang ada di sini?`,
`Siapa orang di antara kita yang menurutmu bisa lolos dari kiamat zombie dan siapa yang akan mati duluan? Beri tahu alasannya!`,
`Buat keputusan, kamu pilih teman atau pacar? Beri alasan yang jelas!`,
`Apa hal terlucu atau memalukan yang pernah kamu alami saat kencan?, jika punya`,
`Di sini, siapa yang menurutmu paling sesuai dengan tipe idealmu?`,
`Di antara kita, siapa orang yang menurutmu paling baik dan paling buruk sifatnya?`,
`Apa hal yang membuatmu senang orang tuamu tidak mengetahuinya?`,
`Bagimu sifat viko di publik gimana?`,
`Kapan terakhir kali kamu menangis, bicara kotor atau lainnya. dan mengapa?`,
`Kamu biasanya sendirian, sedang melakukan kegiatan apa aja?`,
`Di antara kita, siapa orang yang paling kamu suka dalam konteks romantis?`,
`dalam perkembangan jaman seorang pria/wanita, akan lebih cantik & ganteng dimasa depan lagi`,
`Pasti waktu kecil pernah Pura pura kerasukan untuk bertujuan apa?`
]
module.exports = truth;